import { gql, useQuery } from '@apollo/client';
import type { NextPage } from 'next';
import Head from 'next/head';

const basicQuery = gql`
  query MyQuery {
    notes(userId: "foo") {
      title
    }
  }
`;

const Home: NextPage = () => {
  const { loading, error, data } = useQuery(basicQuery);
  console.log(error);
  return (
    <div>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello, Next!
      {loading && <p>Loading...</p>}
      {error && <p>Error:</p>}
      {data && <p>{JSON.stringify(data)}</p>}
    </div>
  );
};

export default Home;
